name: Docker Image CD

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Publish to Entry Container Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: print-admission-ticket
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ secrets.DOCKER_REGISTRY }}
        snapshot: true
